# Generated by Django 4.1 on 2023-11-29 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id_carrera', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30, unique=True)),
                ('vueltas', models.PositiveIntegerField()),
                ('ubicacion', models.CharField(max_length=40)),
                ('fecha', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Carreras',
            },
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id_equipo', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='Clave')),
                ('ciudad', models.CharField(max_length=20, verbose_name='Ciudad')),
                ('nombre', models.CharField(max_length=20, unique=True, verbose_name='Nombre')),
                ('cantidad_competidores', models.PositiveIntegerField(verbose_name='Cantidad de Competidores')),
            ],
            options={
                'verbose_name_plural': 'Equipos',
            },
        ),
        migrations.CreateModel(
            name='Organizador',
            fields=[
                ('id_organizador', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30, unique=True)),
                ('usuario', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('many_carr', models.ManyToManyField(to='posiciones.carrera')),
            ],
            options={
                'verbose_name_plural': 'Organizadores',
            },
        ),
        migrations.CreateModel(
            name='Competidor',
            fields=[
                ('id_competidor', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='Clave')),
                ('nombre', models.CharField(max_length=30, unique=True, verbose_name='Nombre')),
                ('direccion', models.CharField(max_length=40, verbose_name='Direccion')),
                ('telefono', models.CharField(max_length=10, verbose_name='Telefono')),
                ('ciudad', models.CharField(max_length=20, verbose_name='Ciudad')),
                ('estado', models.CharField(max_length=20, verbose_name='Estado')),
                ('CURP', models.CharField(max_length=20, verbose_name='CURP')),
                ('edad', models.PositiveIntegerField(verbose_name='Edad')),
                ('tipo', models.TextField(choices=[('5', 'AB+'), ('1', 'A+'), ('4', 'B-'), ('8', 'O-'), ('2', 'A-'), ('7', 'O+'), ('3', 'B+'), ('6', 'AB-')], verbose_name='Tipo de Sangre')),
                ('id_equipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='posiciones.equipo')),
            ],
            options={
                'verbose_name_plural': 'Competidores',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='Clave')),
                ('nombre', models.CharField(max_length=30, unique=True, verbose_name='Nombre')),
                ('requisitos', models.TextField(blank=True, null=True, verbose_name='Requisitos')),
                ('many_comp', models.ManyToManyField(to='posiciones.competidor')),
            ],
            options={
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='CarreraCompetidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiempo', models.TimeField()),
                ('id_carrera', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='posiciones.carrera')),
                ('id_competidor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='posiciones.competidor')),
            ],
            options={
                'verbose_name_plural': 'Carreras Competidores',
            },
        ),
        migrations.AddField(
            model_name='carrera',
            name='many_carr_comp',
            field=models.ManyToManyField(through='posiciones.CarreraCompetidor', to='posiciones.competidor'),
        ),
    ]
