# Generated by Django 4.2.7 on 2023-11-29 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('fecha', models.DateTimeField()),
                ('vueltas', models.IntegerField()),
                ('ubicacion', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Carreras',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('clv', models.PositiveIntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('can_corredores', models.PositiveIntegerField(default=1)),
                ('hora', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Competidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_categoria', models.IntegerField()),
                ('id_equipo', models.IntegerField()),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=13)),
                ('ciudad', models.CharField(max_length=30)),
                ('estado', models.CharField(max_length=30)),
                ('curp', models.CharField(max_length=18)),
                ('edad', models.IntegerField()),
                ('tipo_sangre', models.CharField(max_length=3)),
            ],
            options={
                'verbose_name_plural': 'Competidores',
            },
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('clv', models.PositiveIntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('ciudad', models.CharField(max_length=30)),
                ('cantidad', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Equipos',
            },
        ),
    ]
