# Generated by Django 4.1 on 2023-11-29 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posiciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competidor',
            name='tipo',
            field=models.TextField(choices=[('8', 'O-'), ('1', 'A+'), ('3', 'B+'), ('7', 'O+'), ('4', 'B-'), ('2', 'A-'), ('5', 'AB+'), ('6', 'AB-')], verbose_name='Tipo de Sangre'),
        ),
    ]
