# Generated by Django 4.1 on 2023-11-30 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posiciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competidor',
            name='tipo',
            field=models.TextField(choices=[('5', 'AB+'), ('8', 'O-'), ('7', 'O+'), ('2', 'A-'), ('1', 'A+'), ('4', 'B-'), ('6', 'AB-'), ('3', 'B+')], verbose_name='Tipo de Sangre'),
        ),
    ]
