# Generated by Django 4.1 on 2023-11-29 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posiciones', '0002_alter_competidor_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrera',
            name='fecha',
            field=models.DateTimeField(help_text='Fecha y hora de la carrera'),
        ),
        migrations.AlterField(
            model_name='competidor',
            name='tipo',
            field=models.TextField(choices=[('3', 'B+'), ('2', 'A-'), ('8', 'O-'), ('5', 'AB+'), ('7', 'O+'), ('4', 'B-'), ('1', 'A+'), ('6', 'AB-')], verbose_name='Tipo de Sangre'),
        ),
    ]
